### ISSUE TITLE
use .config in *nix systems

### ISSUE THREAD

**Issue by undertherain** [mbdevpl/ingit#2]
to keep user's home nice and clean

**Comment by mbdevpl** [comment]
Done in v0.3.0. Now the config location is platform dependent. On Linux, please move your configs to: `~/.config/ingit/ingit_config.json` and `~/.config/ingit/ingit_repos.json` -- or alternatively, delete and let ingit recreate them (of course, with data loss).

Please note that now the config filenames **do not** have dot as the first character.
